alter table public.fan_events
  add column if not exists main_image_path text;

alter table public.fan_events
  add column if not exists updated_at timestamptz not null default now();


drop trigger if exists fan_events_set_updated_at on public.fan_events;

create trigger fan_events_set_updated_at
before update on public.fan_events
for each row
execute function public.set_updated_at();


create table if not exists public.fan_event_images (
  id            bigint generated by default as identity primary key,
  fan_event_id  bigint not null references public.fan_events(id) on delete cascade,
  image_url     text not null,
  storage_path  text not null,
  sort_order    integer not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists fan_event_images_event_id_idx
  on public.fan_event_images (fan_event_id);

create index if not exists fan_event_images_event_sort_idx
  on public.fan_event_images (fan_event_id, sort_order);

create unique index if not exists fan_event_images_event_sort_unique_idx
  on public.fan_event_images (fan_event_id, sort_order);

alter table public.fan_event_images enable row level security;


drop policy if exists "fan_event_images public read" on public.fan_event_images;
create policy "fan_event_images public read"
  on public.fan_event_images
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.fan_events
      where fan_events.id = fan_event_images.fan_event_id
        and fan_events.is_public = true
    )
  );

drop policy if exists "fan_event_images organizer insert" on public.fan_event_images;
create policy "fan_event_images organizer insert"
  on public.fan_event_images
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.fan_events
      where fan_events.id = fan_event_images.fan_event_id
        and fan_events.organizer_profile_id = auth.uid()
    )
  );

drop policy if exists "fan_event_images organizer update" on public.fan_event_images;
create policy "fan_event_images organizer update"
  on public.fan_event_images
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.fan_events
      where fan_events.id = fan_event_images.fan_event_id
        and fan_events.organizer_profile_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.fan_events
      where fan_events.id = fan_event_images.fan_event_id
        and fan_events.organizer_profile_id = auth.uid()
    )
  );

drop policy if exists "fan_event_images organizer delete" on public.fan_event_images;
create policy "fan_event_images organizer delete"
  on public.fan_event_images
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.fan_events
      where fan_events.id = fan_event_images.fan_event_id
        and fan_events.organizer_profile_id = auth.uid()
    )
  );


alter table public.fan_events enable row level security;

drop policy if exists "fan_events public read" on public.fan_events;
create policy "fan_events public read"
  on public.fan_events
  for select
  to anon, authenticated
  using (is_public = true);

drop policy if exists "fan_events organizer insert" on public.fan_events;
create policy "fan_events organizer insert"
  on public.fan_events
  for insert
  to authenticated
  with check (auth.uid() = organizer_profile_id);

drop policy if exists "fan_events organizer update" on public.fan_events;
create policy "fan_events organizer update"
  on public.fan_events
  for update
  to authenticated
  using (auth.uid() = organizer_profile_id)
  with check (auth.uid() = organizer_profile_id);

drop policy if exists "fan_events organizer delete" on public.fan_events;
create policy "fan_events organizer delete"
  on public.fan_events
  for delete
  to authenticated
  using (auth.uid() = organizer_profile_id);

create index if not exists fan_events_start_at_idx
  on public.fan_events (start_at);

create index if not exists fan_events_organizer_idx
  on public.fan_events (organizer_profile_id);

create index if not exists fan_events_public_start_idx
  on public.fan_events (is_public, start_at);


create index if not exists fan_event_attendees_event_idx
  on public.fan_event_attendees (fan_event_id);

create index if not exists fan_event_attendees_profile_idx
  on public.fan_event_attendees (profile_id);

create index if not exists fan_event_attendees_event_profile_idx
  on public.fan_event_attendees (fan_event_id, profile_id);


alter table public.fan_event_attendees enable row level security;

drop policy if exists "fan_event_attendees self read"          on public.fan_event_attendees;
drop policy if exists "fan_event_attendees self write"         on public.fan_event_attendees;
drop policy if exists "fan_event_attendees self update"        on public.fan_event_attendees;
drop policy if exists "fan_event_attendees self delete"        on public.fan_event_attendees;
drop policy if exists "fan_event_attendees public event read"  on public.fan_event_attendees;

create policy "fan_event_attendees public event read"
  on public.fan_event_attendees
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.fan_events
      where fan_events.id = fan_event_attendees.fan_event_id
        and fan_events.is_public = true
    )
  );

create policy "fan_event_attendees self write"
  on public.fan_event_attendees
  for insert
  to authenticated
  with check (auth.uid() = profile_id);

create policy "fan_event_attendees self update"
  on public.fan_event_attendees
  for update
  to authenticated
  using (auth.uid() = profile_id)
  with check (auth.uid() = profile_id);

create policy "fan_event_attendees self delete"
  on public.fan_event_attendees
  for delete
  to authenticated
  using (auth.uid() = profile_id);


insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'event-images',
  'event-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do nothing;


drop policy if exists "Anyone can view event images"               on storage.objects;
create policy "Anyone can view event images"
  on storage.objects
  for select
  to public
  using (bucket_id = 'event-images'::text);

drop policy if exists "Users can upload their own event images"    on storage.objects;
create policy "Users can upload their own event images"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'event-images'::text
    and (storage.foldername(name))[1] = (auth.uid())::text
  );

drop policy if exists "Users can update their own event images"    on storage.objects;
create policy "Users can update their own event images"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'event-images'::text
    and (storage.foldername(name))[1] = (auth.uid())::text
  );

drop policy if exists "Users can delete their own event images"    on storage.objects;
create policy "Users can delete their own event images"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'event-images'::text
    and (storage.foldername(name))[1] = (auth.uid())::text
  );
